FROM oven/bun AS build

WORKDIR /app

COPY package.json .
COPY bun.lockb .
COPY tsconfig.json .

COPY packages/db packages/db
COPY packages/api packages/api

RUN bun install

WORKDIR /app/packages/api

RUN bun build \
    --compile \
    --minify \
    --target bun \
    --outfile server \
    ./src/index.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/packages/api/server ./server

ENV ENV=production
ENV NODE_ENV=production

EXPOSE 3000

CMD ["./server"]
