# fly.toml app configuration file generated for latch-web-1337 on 2024-12-27T09:25:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'latch-web-1337'
primary_region = 'arn'

[build]
  dockerfile = './Dockerfile.web'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  VITE_API_URL = "https://latch-api-1337.fly.dev"
  VITE_ENV = "production"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
