app = 'latch-web-1337'
primary_region = 'arn'

[build]
  dockerfile = './Dockerfile.web'

  [build.args]
    VITE_API_URL = "https://latch-api-1337.fly.dev"
    VITE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
