# fly.toml app configuration file generated for latch-falling-pond-1256 on 2024-12-25T23:52:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "latch-falling-pond-1256"
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
