version: "3"
services:
  zero-cache:
    image: rocicorp/zero-cache
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_DB_URL_1}
      - ZERO_CVR_DB=${ZERO_DB_URL_2}
      - ZERO_CHANGE_DB=${ZERO_DB_URL_3}
      - ZERO_REPLICA_FILE=/data/zero-replica.db
      - ZERO_SCHEMA_FILE=/zero/zero-schema.json
      - ZERO_AUTH_SECRET=${JWT_SECRET}
      - ZERO_PORT=4848
      - ZERO_AUTO_RESET=true # Helpful during development
    volumes:
      - ./data:/data
    ports:
      - "4848:4848"
    command: sh -c "zero-cache-dev"
